import {useEffect, useState} from 'react'

import Head from 'next/head'

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';

import Navbar from '../components/Navbar'

import { getAuthor, getBooks } from '../utils/api/authors';
import { AuthorInfo } from '../components/AuthorInfo';
import { BooksTable } from '../components/BooksTable';
import { PopularAuthorList } from '../components/PopularAuthorList';

export default function Home() {
  const [authorKey, setAuthorKey] = useState("OL23919A")
  const [authorData, setAuthorData] = useState([])
  const [authorBooks, setAuthorBooks] = useState([])

  useEffect(() => {
    getAuthor(authorKey).then((data) => {
      console.log(data)
      setAuthorData(data)
    })
  }, [authorKey])

  useEffect(() => {
    getBooks(authorKey).then((data) => {
      console.log(data)
      setAuthorBooks(data)
    })
  }, [authorKey])

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <Box>
                <AuthorInfo
                authorData={authorData}
                />
                <BooksTable
                authorBooks={authorBooks}
                />
              </Box>
            </Grid>
            <Grid item xs={4}>
              <PopularAuthorList
              setAuthorKey={setAuthorKey}
              />
            </Grid>
          </Grid>
          
        </Container>
      </main>
    </div>
  )
}
