import { Container } from '@mui/system'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Typography } from '@mui/material'

import "@fontsource/roboto"

import JSArticles from '../components/JSArticles'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container>
          <Typography
          variant='h2'
          component='h2'
          color='primary'
          align='center'
          >
            Assignment 2 - React Components and Styling
          </Typography>
          <Typography
          color='secondary'
          align='center'
          >
            Here's a list of awesome resources that you can use
          </Typography>
          <JSArticles/>
        </Container>
        
      </main>
    </div>
  )
}
