import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import Hello from '@/components/Hello'
import NewConcept from '@/components/NewConcept'
import ComponentWrapper from '@/components/ComponentWrapper'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ComponentWrapper textColor="blue">
          <h1>Fundamental Components Example</h1>
          <Hello />
          <NewConcept concept='naming the component the same as the file'/>
          <NewConcept concept='weird babel errors that Dan will look at'/>
        </ComponentWrapper>
      </main>
    </>
  )
}
